var sms = new Sms();
//sms.loadRom('output.sms');
//sms.loadRom('zexall.sms');
//sms.loadRom('Racer.sms');
//sms.loadRom('Castle of Illusion.sms');
//sms.loadRom('Sonic The Hedgehog.sms');
//sms.loadRom('Sonic The Hedgehog 2.sms');
//sms.loadRom('Sonic Chaos.sms');
//sms.loadRom('Alex Kidd in Miracle World.sms');
//sms.loadRom('G-Loc Air Battle.sms');
//sms.loadRom('Mortal Kombat 3.sms');
//sms.loadRom('Michael Jackson\'s Moonwalker.sms');
//sms.loadRom('Shinobi.sms');
//sms.loadRom('Alex Kidd the Lost Stars.sms');
//sms.loadRom('Ghostbusters.sms');
//sms.loadRom('Duckslayer Adventures.sms');
//sms.loadRom('Raster Parallax.sms');
//sms.loadRom('Candy Kid Demo.sms');
//sms.loadRom('TestSuite.sms');
//sms.loadRom('VDPTEST.sms');
//sms.loadRom('64 Colours Rasters.sms');
//sms.loadRom('Bad Apple.sms');
//sms.loadRom('Super Mario Clouds.sms');
//sms.loadRom('Photo.sms');

